export const DAILY_LOAD_LIST="DAILY_LOAD_LIST"
export const DAILY_LOAD_LIST_FAILED="DAILY_LOAD_LIST_FAILED"
export const DAILY_LOAD_LIST_SUCCESS="DAILY_LOAD_LIST_SUCCESS"

export const DAILY_CHANGE_DATE_START="DAILY_CHANGE_DATE_START"
export const DAILY_CHANGE_DATE_END="DAILY_CHANGE_DATE_END"
