export const BRANCH_LOAD_LIST="BRANCH_LOAD_LIST"
export const BRANCH_LOAD_LIST_FAILED="BRANCH_LOAD_LIST_FAILED"
export const BRANCH_LOAD_LIST_SUCCESS="BRANCH_LOAD_LIST_SUCCESS"

export const BRANCH_LOAD_ADD_FORM="BRANCH_LOAD_ADD_FORM"
export const BRANCH_SAVE_FORM="BRANCH_SAVE_FORM"
export const BRANCH_SAVE_FAILED_FORM="BRANCH_SAVE_FAILED_FORM"
export const BRANCH_SAVE_SUCCESS_FORM="BRANCH_SAVE_SUCCESS_FORM"

export const BRANCH_LOAD_FORM_SUCCESS="BRANCH_LOAD_FORM_SUCCESS"
export const BRANCH_LOAD_FORM_FAILED="BRANCH_LOAD_FORM_FAILED"

export const BRANCH_LOAD_EDIT_FORM="BRANCH_LOAD_EDIT_FORM"
export const BRANCH_UPDATE_SUCCESS_FORM="BRANCH_UPDATE_SUCCESS_FORM"

export const BRANCH_FORM_VALUE_CHANGED="BRANCH_FORM_VALUE_CHANGED"
export const BRANCH_FORM_HEAD_VALUE_CHANGED="BRANCH_FORM_HEAD_VALUE_CHANGED"

export const BRANCH_LOAD_DELETE_DIALOG="BRANCH_LOAD_DELETE_DIALOG"
export const BRANCH_DELETE_ATTEMPT="BRANCH_DELETE_ATTEMPT"
export const BRANCH_DELETE_FAILED="BRANCH_DELETE_FAILED"
export const BRANCH_DELETE_SUCCESS="BRANCH_DELETE_SUCCESS"
export const BRANCH_CANCEL_DELETE="BRANCH_CANCEL_DELETE"