export const POL_LOAD_LIST="POL_LOAD_LIST"
export const POL_LOAD_LIST_FAILED="POL_LOAD_LIST_FAILED"
export const POL_LOAD_LIST_SUCCESS="POL_LOAD_LIST_SUCCESS"

export const POL_LOAD_ADD_FORM="POL_LOAD_ADD_FORM"
export const POL_SAVE_FORM="POL_SAVE_FORM"
export const POL_SAVE_FAILED_FORM="POL_SAVE_FAILED_FORM"
export const POL_SAVE_SUCCESS_FORM="POL_SAVE_SUCCESS_FORM"

export const POL_LOAD_FORM_SUCCESS="POL_LOAD_FORM_SUCCESS"
export const POL_LOAD_FORM_FAILED="POL_LOAD_FORM_FAILED"

export const POL_LOAD_EDIT_FORM="POL_LOAD_EDIT_FORM"
export const POL_UPDATE_SUCCESS_FORM="POL_UPDATE_SUCCESS_FORM"

export const POL_FORM_VALUE_CHANGED="POL_FORM_VALUE_CHANGED"
export const POL_LOAD_DELETE_DIALOG="POL_LOAD_DELETE_DIALOG"
export const POL_DELETE_ATTEMPT="POL_DELETE_ATTEMPT"
export const POL_DELETE_FAILED="POL_DELETE_FAILED"
export const POL_DELETE_SUCCESS="POL_DELETE_SUCCESS"
export const POL_CANCEL_DELETE="POL_CANCEL_DELETE"
