export const LT_LOAD_LIST="LT_LOAD_LIST"
export const LT_LOAD_LIST_FAILED="LT_LOAD_LIST_FAILED"
export const LT_LOAD_LIST_SUCCESS="LT_LOAD_LIST_SUCCESS"

export const LT_LOAD_ADD_FORM="LT_LOAD_ADD_FORM"
export const LT_SAVE_FORM="LT_SAVE_FORM"
export const LT_SAVE_FAILED_FORM="LT_SAVE_FAILED_FORM"
export const LT_SAVE_SUCCESS_FORM="LT_SAVE_SUCCESS_FORM"

export const LT_LOAD_FORM_SUCCESS="LT_LOAD_FORM_SUCCESS"
export const LT_LOAD_FORM_FAILED="LT_LOAD_FORM_FAILED"

export const LT_LOAD_EDIT_FORM="LT_LOAD_EDIT_FORM"
export const LT_UPDATE_SUCCESS_FORM="LT_UPDATE_SUCCESS_FORM"

export const LT_FORM_VALUE_CHANGED="LT_FORM_VALUE_CHANGED"
export const LT_FORM_LINKID_VALUE_CHANGED="LT_FORM_LINKID_VALUE_CHANGED"

export const LT_LOAD_DELETE_DIALOG="LT_LOAD_DELETE_DIALOG"
export const LT_DELETE_ATTEMPT="LT_DELETE_ATTEMPT"
export const LT_DELETE_FAILED="LT_DELETE_FAILED"
export const LT_DELETE_SUCCESS="LT_DELETE_SUCCESS"
export const LT_CANCEL_DELETE="LT_CANCEL_DELETE"