export const JOB_LOAD_LIST="JOB_LOAD_LIST"
export const JOB_LOAD_LIST_FAILED="JOB_LOAD_LIST_FAILED"
export const JOB_LOAD_LIST_SUCCESS="JOB_LOAD_LIST_SUCCESS"

export const JOB_LOAD_ADD_FORM="JOB_LOAD_ADD_FORM"
export const JOB_SAVE_FORM="JOB_SAVE_FORM"
export const JOB_SAVE_FAILED_FORM="JOB_SAVE_FAILED_FORM"
export const JOB_SAVE_SUCCESS_FORM="JOB_SAVE_SUCCESS_FORM"

export const JOB_LOAD_FORM_SUCCESS="JOB_LOAD_FORM_SUCCESS"
export const JOB_LOAD_FORM_FAILED="JOB_LOAD_FORM_FAILED"

export const JOB_LOAD_EDIT_FORM="JOB_LOAD_EDIT_FORM"
export const JOB_UPDATE_SUCCESS_FORM="JOB_UPDATE_SUCCESS_FORM"

export const JOB_FORM_VALUE_CHANGED="JOB_FORM_VALUE_CHANGED"
export const JOB_LOAD_DELETE_DIALOG="JOB_LOAD_DELETE_DIALOG"
export const JOB_DELETE_ATTEMPT="JOB_DELETE_ATTEMPT"
export const JOB_DELETE_FAILED="JOB_DELETE_FAILED"
export const JOB_DELETE_SUCCESS="JOB_DELETE_SUCCESS"
export const JOB_CANCEL_DELETE="JOB_CANCEL_DELETE"