
export const EMP_LOAD_LIST="EMP_LOAD_LIST"
export const EMP_LOAD_SUCCESS_LIST="EMP_LOAD_SUCCESS_LIST"
export const EMP_LOAD_FAILED_LIST="EMP_LOAD_FAILED_LIST"

export const EMP_LOAD_FORM="EMP_LOAD_FORM"
export const EMP_LOAD_SUCCESS_FORM="EMP_LOAD_SUCCESS_FORM"
export const EMP_LOAD_FAILED_FORM="EMP_LOAD_FAILED_FORM"
export const EMP_SAVE_FORM="EMP_SAVE_FORM"
export const EMP_SAVE_FAILED_FORM="EMP_SAVE_FAILED_FORM"
export const EMP_SAVE_SUCCESS_FORM="EMP_SAVE_SUCCESS_FORM"
export const EMP_FORM_VALUE_CHANGED="EMP_FORM_VALUE_CHANGED"
export const EMP_FORM_CIVIL_CHANGED="EMP_FORM_CIVIL_CHANGED"
export const EMP_FORM_GENDER_CHANGED="EMP_FORM_GENDER_CHANGED"

