
export const LOAD_FORM="LOAD_ADD_FORM"
export const LOAD_SUCCESS_FORM="LOAD_SUCCESS_FORM"
export const LOAD_FAILED_FORM="LOAD_FAILED_FORM"
export const SAVE_FORM="SAVE_FORM"
export const SAVE_FAILED_FORM="SAVE_FAILED_FORM"
export const SAVE_SUCCESS_FORM="SAVE_SUCCESS_FORM"
export const FORM_VALUE_CHANGED="FORM_VALUE_CHANGED"
