export const SHIFT_LOAD_LIST="SHIFT_LOAD_LIST"
export const SHIFT_LOAD_LIST_FAILED="SHIFT_LOAD_LIST_FAILED"
export const SHIFT_LOAD_LIST_SUCCESS="SHIFT_LOAD_LIST_SUCCESS"

export const SHIFT_LOAD_ADD_FORM="SHIFT_LOAD_ADD_FORM"
export const SHIFT_SAVE_FORM="SHIFT_SAVE_FORM"
export const SHIFT_SAVE_FAILED_FORM="SHIFT_SAVE_FAILED_FORM"
export const SHIFT_SAVE_SUCCESS_FORM="SHIFT_SAVE_SUCCESS_FORM"

export const SHIFT_LOAD_FORM_SUCCESS="SHIFT_LOAD_FORM_SUCCESS"
export const SHIFT_LOAD_FORM_FAILED="SHIFT_LOAD_FORM_FAILED"

export const SHIFT_LOAD_EDIT_FORM="SHIFT_LOAD_EDIT_FORM"
export const SHIFT_UPDATE_SUCCESS_FORM="SHIFT_UPDATE_SUCCESS_FORM"

export const SHIFT_FORM_VALUE_CHANGED="SHIFT_FORM_VALUE_CHANGED"
export const SHIFT_LOAD_DELETE_DIALOG="SHIFT_LOAD_DELETE_DIALOG"
export const SHIFT_DELETE_ATTEMPT="SHIFT_DELETE_ATTEMPT"
export const SHIFT_DELETE_FAILED="SHIFT_DELETE_FAILED"
export const SHIFT_DELETE_SUCCESS="SHIFT_DELETE_SUCCESS"
export const SHIFT_CANCEL_DELETE="SHIFT_CANCEL_DELETE"