export const HOL_LOAD_LIST="HOL_LOAD_LIST"
export const HOL_LOAD_LIST_FAILED="HOL_LOAD_LIST_FAILED"
export const HOL_LOAD_LIST_SUCCESS="HOL_LOAD_LIST_SUCCESS"

export const HOL_LOAD_ADD_FORM="HOL_LOAD_ADD_FORM"
export const HOL_SAVE_FORM="HOL_SAVE_FORM"
export const HOL_SAVE_FAILED_FORM="HOL_SAVE_FAILED_FORM"
export const HOL_SAVE_SUCCESS_FORM="HOL_SAVE_SUCCESS_FORM"

export const HOL_LOAD_FORM_SUCCESS="HOL_LOAD_FORM_SUCCESS"
export const HOL_LOAD_FORM_FAILED="HOL_LOAD_FORM_FAILED"

export const HOL_LOAD_EDIT_FORM="HOL_LOAD_EDIT_FORM"
export const HOL_UPDATE_SUCCESS_FORM="HOL_UPDATE_SUCCESS_FORM"

export const HOL_FORM_VALUE_CHANGED="HOL_FORM_VALUE_CHANGED"
export const HOL_LOAD_DELETE_DIALOG="HOL_LOAD_DELETE_DIALOG"
export const HOL_DELETE_ATTEMPT="HOL_DELETE_ATTEMPT"
export const HOL_DELETE_FAILED="HOL_DELETE_FAILED"
export const HOL_DELETE_SUCCESS="HOL_DELETE_SUCCESS"
export const HOL_CANCEL_DELETE="HOL_CANCEL_DELETE"
